[build-system]
requires = [ "setuptools>=41", "wheel", "setuptools-git-versioning>=2.0,<3", ]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true
version_file = "horizon/VERSION"
count_commits_from_version_file = true
dev_template = "{tag}.dev{env:GITHUB_RUN_ID:{ccount}}+git.{sha}"
dirty_template = "{tag}.dev{env:GITHUB_RUN_ID:{ccount}}+git.{sha}.dirty"

[project]
name = "data-horizon"
license = { file = "LICENSE.txt" }
description = "Horizon REST API + client"
authors = [{name= "MWS Data Bridge", email = "onetools@mts.ru"}]
readme = "README.rst"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Pydantic",
    "Framework :: Pydantic :: 1",
    "Framework :: Pydantic :: 2",
    "Framework :: FastAPI",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
keywords = ["Horizon", "REST", "API", "HWM"]
requires-python = ">=3.7"
dependencies = [
    "pydantic<3",
    "typing-extensions>=4.0.0",
]
dynamic = ["version"]

[tool.setuptools.packages.find]
include = ["horizon*"]
exclude = ["docs", "tests"]

[tool.setuptools.package-data]
"*" = ["py.typed", "*.yml",  "*.ini", "VERSION"]

[project.urls]  # Optional
"Homepage" = "https://github.com/MobileTeleSystems/horizon"
"Documentation" = "https://data-horizon.readthedocs.io/"
"Source" = "https://github.com/MobileTeleSystems/horizon"
"CI/CD" = "https://github.com/MobileTeleSystems/horizon/actions"
"Tracker" = "https://github.com/MobileTeleSystems/horizon/issues"


[project.optional-dependencies]
backend = [
    "pydantic-settings",
    "fastapi>=0.103.2",
    "starlette",
    "python-multipart",
    "anyio",
    "starlette-exporter",
    "uvicorn",
    "alembic",
    "sqlalchemy>=2.0",
    "sqlalchemy-utils",
    "greenlet>=3.1.1",
    "asgi-correlation-id",
    "python-json-logger",
    "coloredlogs",
    "pyyaml",
    "uuid6",
    "devtools",
    "passlib",
    "authlib",
]
postgres = [
    "asyncpg",
]
client-sync = [
    "packaging",
    "requests",
    "urllib3>=1.26.0",
]
ldap = [
    "bonsai>=1.5.3",
    "argon2-cffi",
]

[dependency-groups]
# pytest-lazy-fixture doesn't support pytest 8.x+
test = [
  "pytest~=7.4.4",
  "httpx>=0.24.1",
  # TODO: upgrading pytest-asyncio requires updating all fixtures https://github.com/pytest-dev/pytest-asyncio/issues/706
  "pytest-asyncio~=0.21.1",
  "pytest-randomly>=3.12.0",
  "pytest-deadfixtures~=3.0.0",
  "pytest-rerunfailures>=13.0",
  "pytest-lazy-fixture~=0.6.3",
  "coverage>=7.2.7",
  "psycopg2-binary>=2.9.9",
  "gevent>=22.10.2",
  "responses>=0.23.2",
]
dev = [
  "prek~=0.2.25",
  "mypy~=1.19.0",
  "sqlalchemy[mypy]~=2.0.44",
  "types-pyyaml~=6.0.12",
  "types-authlib~=1.6.6",
  "types-passlib~=1.7.7",
  "types-requests~=2.32.4",
]
docs = [
  "setuptools-git-versioning~=2.1.0",
  "autodoc-pydantic~=2.2.0",
  "numpydoc~=1.10.0",
  # sphinx-design doesn't support sphinx 9
  "sphinx<9",
  "furo>=2025.9.25,<2025.13.0",
  "sphinx-copybutton~=0.5.2",
  "sphinxcontrib-towncrier~=0.5.0a0",
  "towncrier~=25.8.0",
  "sphinx-issues~=5.0.1",
  "sphinx-design~=0.6.1",
  "sphinx-favicon~=1.0.1",
  "sphinx-argparse~=0.5.2",
  # https://github.com/mgeier/sphinx-last-updated-by-git/pull/77
  "sphinx-last-updated-by-git~= 0.3.8",
  # uncomment after https://github.com/zqmillet/sphinx-plantuml/pull/4
  # "sphinx-plantuml~=1.0.0",
]

[tool.uv]
default-groups = []

[tool.uv.dependency-groups]
dev = {requires-python = ">=3.10"}
docs = {requires-python = ">=3.10"}


[tool.pytest.ini_options]
markers = [
    "backend: tests for backend (require running database)",
    "client: tests for horizon-client (require running database and backend)",
    "client_sync: tests for HorizonClientSync (using requests)",
    "auth: tests using AuthProvider",
    "dummy_auth: tests for DummyAuthProvider",
    "ldap_auth: tests for LDAPAuthProvider",
]

[tool.coverage.paths]
source = ["horizon"]

[tool.coverage.run]
branch = true
parallel = true
relative_files = true
concurrency = ["gevent"]
omit = [
  "tests/*",
]
data_file = "reports/.coverage"

[tool.coverage.report]
precision = 2
exclude_also = [
  "def __repr__",
  "raise AssertionError",
  "raise NotImplementedError",
  "@(abc\\.)?abstractmethod",
  "\\.\\.\\.",
  "def downgrade\\(\\)",
  "if .*TYPE_CHECKING:",
  "if .*isEnabledFor.*:",
  "if .*debug.*:",
  "if .*sys.version_info.*:",
  "if __name__ == .__main__.:",
]
[tool.ruff]
target-version = "py37"
line-length = 120
extend-exclude = ["docs/", "Makefile"]

[tool.ruff.lint]
select = ["ALL"]
# UP035, UP006 - Set -> set, Dict -> dict... ignore for support python version before 3.9
# FA100, UP045 - Optional[str] -> str | None, doesn't work before 3.10
# B905 - zip(strict=True) was added in Python 3.9
ignore = ["ARG", "ANN", "D", "COM812", "TD", "FIX002", "FA100", "UP035", "UP006", "UP007", "UP045"]

[tool.ruff.lint.per-file-ignores]
"horizon/commons/schemas/*" = ["TC"]
"horizon/backend/middlewares/*" = ["TC"]
"horizon/backend/db/repositories/*" = ["TC"]
"horizon/backend/db/migrations/*" = ["INP001", "E501"]
"horizon/backend/providers/auth/*" = ["PLR0913"]

"tests/*" = ["S", "A", "PLR0913", "PLR2004", "FBT001", "SLF001"]
"tests/*/fixtures/*" = ["INP001"]
"tests/fixtures/*" = ["INP001"]

[tool.ruff.lint.flake8-pytest-style]
parametrize-names-type = "list"
parametrize-values-type = "list"
parametrize-values-row-type = "tuple"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.ruff.lint.flake8-errmsg]
max-string-length=20

[tool.codespell]
exclude-file = "uv.lock"
ignore-words-list = "selectin"

[tool.towncrier]
name = "Horizon"
package = "horizon"
filename = "docs/changelog/NEXT_RELEASE.rst"
directory = "docs/changelog/next_release/"
title_format = "{version} ({project_date})"
issue_format = ":issue:`{issue}`"

[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "significant"
name = "Significant Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "improvement"
name = "Improvements"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "dependency"
name = "Dependencies"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Doc only Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Misc"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Removal"
showcontent = true
