# syntax = docker/dockerfile:1.4

ARG PYTHON_VERSION=3.13
FROM python:$PYTHON_VERSION-slim AS base

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        # Used for healthcheck
        curl \
    && rm -rf /var/lib/apt/lists/* /var/cache/*

WORKDIR /app
ENV PYTHONPATH=/app \
    PATH="/app/.venv/bin:$PATH"

# Logo
COPY --chmod=644 docs/_static/*.svg /app/horizon/backend/static/

# Swagger UI
ADD --chmod=644 https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui-bundle.js https://cdn.jsdelivr.net/npm/swagger-ui-dist@latest/swagger-ui.css \
    /app/horizon/backend/static/swagger/

# Redoc
ADD --chmod=644 https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js /app/horizon/backend/static/redoc/redoc.standalone.js

ENV HORIZON__SERVER__OPENAPI__SWAGGER__JS_URL=/static/swagger/swagger-ui-bundle.js \
    HORIZON__SERVER__OPENAPI__SWAGGER__CSS_URL=/static/swagger/swagger-ui.css \
    HORIZON__SERVER__OPENAPI__REDOC__JS_URL=/static/redoc/redoc.standalone.js \
    HORIZON__SERVER__STATIC_FILES__DIRECTORY=/app/horizon/backend/static

COPY --chmod=755 ./docker/entrypoint.sh /app/docker/entrypoint.sh
ENTRYPOINT ["/app/docker/entrypoint.sh"]
EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD ["curl", "-f", "http://localhost:8000/monitoring/ping"]


FROM base AS builder

# required for building bonsai
RUN apt-get update && apt-get install -y \
        libkrb5-dev \
        libsasl2-dev \
        libsasl2-modules-gssapi-mit \
        libsasl2-modules-ldap \
        libsasl2-modules \
        libssl-dev \
        libldap2-dev \
        autoconf \
        gcc \
        g++ \
        make \
        libnghttp2-dev \
        libffi-dev \
    && rm -rf /var/lib/apt/lists/* /var/cache/*

# uv package in PyPI requires Python>=3.8, but we need 3.7
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/bin/uv

COPY ./pyproject.toml ./uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync \
        --frozen \
        --no-install-project \
        --all-extras \
        --compile-bytecode


FROM base AS prod

COPY --link --from=builder /app/.venv/ /app/.venv/

COPY ./horizon/ /app/horizon/
RUN python -m compileall -b horizon

# Do not run production as root, to improve security.
# Also user does not own anything inside the image, including venv and source code.
RUN useradd horizon
USER horizon


FROM builder AS test

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync \
        --frozen \
        --no-install-project \
        --all-extras \
        --group "test" \
        --compile-bytecode

RUN sed -i 's/python -m/coverage run -m/g' /app/docker/entrypoint.sh
